apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: civicpulse
resources:
- ../../base
images:
- name: civicpulse-backend
  newName: ghcr.io/at3692/civicpulse-backend
  newTag: replace-with-commit-sha
- name: civicpulse-frontend
  newName: ghcr.io/at3692/civicpulse-frontend
  newTag: replace-with-commit-sha
