apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: civicpulse
resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- backend.yaml
- frontend.yaml
- postgres.yaml
- redis.yaml
- ingress.yaml
- hpa.yaml
- pdb.yaml
- migrate.yaml
- networkpolicy.yaml
